name: pagila

services:
  app:
    build:
      context: .
      dockerfile: "app.Dockerfile"
      args:
        - AIRVISUAL_KEY=${AIRVISUAL_KEY}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_PORT=${POSTGRES_PORT}
        - POSTGRES_DATABASE=${POSTGRES_DATABASE}
        - WEATHER_KEY=${WEATHER_KEY}
    container_name: app
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - public
  db:
    image: postgres:17
    container_name: db
    env_file:
      - .env
    restart: always
    shm_size: 128mb
    networks:
      - public
    expose:
      - "5433"
    ports:
      - "5433:5432"
    volumes:
      - ./scripts/pagila-schema.sql:/docker-entrypoint-initdb.d/1-pagila-schema.sql
      - ./scripts/pagila-schema-jsonb.sql:/docker-entrypoint-initdb.d/1-pagila-schema-jsonb.sql
      - ./scripts/pagila-data.sql:/docker-entrypoint-initdb.d/2-pagila-data.sql
      - ./scripts/restore-pagila-data-jsonb.sh:/docker-entrypoint-initdb.d/3-restore-pagila-data-jsonb.sh
      - ./scripts/pagila-data-yum-jsonb.backup:/docker-entrypoint-initdb.d/pagila-data-yum-jsonb.backup
      - ./scripts/pagila-data-apt-jsonb.backup:/docker-entrypoint-initdb.d/pagila-data-apt-jsonb.backup
      - pgdata:/var/lib/postgresql/data


networks:
  public:

volumes:
  pgdata: